substitutions:
  devicename: "esp12f-8c-aa-b5-78-2e-23"
  upper_devicename: Aquarium-Dimmer
 
  update_time: 5s

esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "69cb9496b19771edbbbdb033b4bf9459"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret hotspot_ssid
    password: !secret hotspot_password

captive_portal:

web_server:
  port: 80


# Example configuration entry
output:
#  - platform: esp8266_pwm
#    pin: 12
#    frequency: 20000 Hz
#    id: pwm_output_2
  - platform: esp8266_pwm
    pin: 12
    id: pwm_output_2
#    power_supply: power_supply_2
#    inverted: false
    frequency: 20000 Hz
    min_power: 0.0001
    max_power: 1.0

# Example usage in a light
light:
  - platform: monochromatic
    output: pwm_output_2
    name: "Licht im Aquarium"