# Your Wi-Fi SSID and password
wifi_ssid: "PowerNetSystem"
wifi_password: "DieMachtIstMitDir"

# Fallback Hotspot
hotspot_ssid: "${upper_devicename} Hotspot"
hotspot_password: "E7P97HqkqfsSjGHqG8Z9tCVC7"

# OTA Password
ota_password: "qo4qkuzqwbwaa9puyksh9knmh6cq4gbi"

# Webserver Zugang
loginname: "Admin"
loginpassword: "Tosca1305#"