esphome:
  name: "stromzaehler"

esp8266:
  board: esp01_1m

# Enable logging
logger:
  hardware_uart: UART1

# Enable Home Assistant API
api:

ota:
  password: "0d5a23981d8b5e62533dec16e9b654a9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Stromzaehler Fallback Hotspot"
    password: "hUF7b4nips3E"

captive_portal:
    
time:
  - platform: homeassistant
    id: homeassistant_time

web_server:
  port: 80
  auth:
    username: admin
    password: Tosca1305#

uart:
  id: uart_bus
  rx_pin: GPIO3
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

sml:
  id: mysml
  uart_id: uart_bus

sensor:
  - platform: sml
    name: "Smart Meter Total Count"
    sml_id: mysml
    id: sml_count
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.00000001
      
  - platform: sml
    name: "Current Total energy"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: power
    state_class: measurement
    filters:
      - multiply: 0.00001
  
  - platform: sml
    name: "Current L1 energy"
    sml_id: mysml
    obis_code: "1-0:36.7.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.00001
      
  - platform: sml
    name: "Current L2 energy"
    sml_id: mysml
    obis_code: "1-0:56.7.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.00001
      
  - platform: sml
    name: "Current L3 energy"
    sml_id: mysml
    obis_code: "1-0:76.7.0"
    unit_of_measurement: kWh
    accuracy_decimals: 4
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.00001
      
  - platform: sml
    name: "Voltage L1"
    sml_id: mysml
    obis_code: "1-0:32.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: power
    state_class: total_increasing
    filters:
      - multiply: 0.1
      
  - platform: sml
    name: "Voltage L2"
    sml_id: mysml
    obis_code: "1-0:52.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: power
    state_class: total_increasing
    filters:
      - multiply: 0.1
      
  - platform: sml
    name: "Voltage L3"
    sml_id: mysml
    obis_code: "1-0:72.7.0"
    unit_of_measurement: V
    accuracy_decimals: 1
    device_class: power
    state_class: total_increasing
    filters:
      - multiply: 0.1

text_sensor:
  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    obis_code: "129-129:199.130.3"
    format: text

  - platform: sml
    name: "Total energy text"
    obis_code: "1-0:1.8.0"
    format: uint