esphome:
  name: wetterbox

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "FPF13ZD9Odz2JpvKbXfJgdfmlW7uE3l4zFTph+kj3To="

ota:
  password: "de95dce5a2ccc44a40a55f0833d2faae"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
   ssid: !secret hotspot_ssid
   password: !secret hotspot_password

captive_portal:
    
web_server:
  port: 80

i2c:
  sda: 5
  scl: 4
  scan: true
  id: i2c0

dallas:
  pin: 12

sensor:
  - platform: bh1750
    id: bh1750_illuminance
    state_class: "measurement"
    device_class: "illuminance"
    unit_of_measurement: "lx"
    name: "Lichtstärke Sensor"
    i2c_id: i2c0
    update_interval: 60s

#  - platform: dallas
#    address: 0x773c01f096c1ee28
#    name: "Aussentemperatur_Wetterbox"