esphome:
  name: <NAME_OF_NODE>

esp8266:
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 1"
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button 2"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Relay 1"
    pin: GPIO15
    id: relay1
  - platform: gpio
    name: "Relay 2"
    pin: GPIO03
    id: relay2

status_led:
  pin:
    number: GPIO00
    inverted: yes
    
sensor:
  - platform: hlw8012
    sel_pin: GPIO12
    cf_pin: GPIO04
    cf1_pin: GPIO05
    current:
      name: "HLW8012 Current"
    voltage:
      name: "HLW8012 Voltage"
    power:
      name: "HLW8012 Power"
    energy:
      name: "HLW8012 Energy"
    update_interval: 60s
    
 output:
  - platform: ledc
    pin: GPIO14
    id: rtttl_out

rtttl:
  output: rtttl_out
